import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const tenant = await prisma.tenant.findFirst({ where: { ativo: true } })
  if (!tenant) throw new Error('Nenhum tenant encontrado')
  console.log(`✓ Tenant: ${tenant.nome} (${tenant.id})`)

  const existente = await prisma.checklistModelo.findFirst({
    where: { tenantId: tenant.id, nome: 'Checklist SMEL' },
  })
  if (existente) {
    console.log('⏭  Checklist SMEL já existe — pulando.')
    return
  }

  const checklist = await prisma.checklistModelo.create({
    data: {
      tenantId: tenant.id,
      nome: 'Checklist SMEL',
      descricao: 'Checklist oficial da Secretaria Municipal de Educação de Luziânia — Nutricionistas. Abrange higiene pessoal, controle da merenda, estrutura e instalações, equipamentos e utensílios, e procedimentos operacionais padrão.',
      categoria: 'OUTRO',
      categoriaPersonalizada: 'SMEL — Nutricionistas',
      frequencia: 'SEMANAL',
      ativo: true,
      isTemplate: true,
      itens: {
        create: [
          // ── 1. Higiene Pessoal ────────────────────────────────────
          {
            ordem: 1,
            secao: '1 - Higiene Pessoal',
            pergunta: 'Uniforme limpo e completo (touca, avental, sapato fechado)',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 2,
            secao: '1 - Higiene Pessoal',
            pergunta: 'Unhas curtas, sem esmalte e sem adornos',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 3,
            secao: '1 - Higiene Pessoal',
            pergunta: 'Lavagem correta e frequente das mãos',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 4,
            secao: '1 - Higiene Pessoal',
            pergunta: 'Ausência de sintomas de doenças infectocontagiosas',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 3.0,
            opcoes: [],
          },

          // ── 2. Controle da merenda ────────────────────────────────
          {
            ordem: 5,
            secao: '2 - Controle da merenda',
            pergunta: 'A merenda está com aspecto e cheiro agradável?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 6,
            secao: '2 - Controle da merenda',
            pergunta: 'O cardápio do dia está conforme o cardápio elaborado pelas nutricionistas?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 7,
            secao: '2 - Controle da merenda',
            pergunta: 'A contagem dos alunos é realizada diariamente?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 8,
            secao: '2 - Controle da merenda',
            pergunta: 'A distribuição da merenda está sendo feita dentro dos padrões estabelecidos?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 9,
            secao: '2 - Controle da merenda',
            pergunta: 'Controle diário está sendo feito corretamente?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 10,
            secao: '2 - Controle da merenda',
            pergunta: 'Não há itens sobrando ou faltando no depósito?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 11,
            secao: '2 - Controle da merenda',
            pergunta: 'As colheres, pratos e copos são suficientes?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 12,
            secao: '2 - Controle da merenda',
            pergunta: 'Está sendo feita a pesagem das sobras limpas e sobras sujas do lanche e lançado no sistema?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 13,
            secao: '2 - Controle da merenda',
            pergunta: 'Acontece a coleta das amostras de água e de comida diariamente?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },

          // ── 3. Estrutura e Instalações ────────────────────────────
          {
            ordem: 14,
            secao: '3 - Estrutura e Instalações',
            pergunta: 'Cozinha limpa, organizada e arejada',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.5,
            opcoes: [],
          },
          {
            ordem: 15,
            secao: '3 - Estrutura e Instalações',
            pergunta: 'Piso, paredes e teto em bom estado',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 16,
            secao: '3 - Estrutura e Instalações',
            pergunta: 'Ventilação adequada',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 17,
            secao: '3 - Estrutura e Instalações',
            pergunta: 'Presença de telas em janelas e portas (controle de pragas)',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },

          // ── 4. Equipamentos e Utensílios ──────────────────────────
          {
            ordem: 18,
            secao: '4 - Equipamentos e Utensílios',
            pergunta: 'Fogão, freezer, forno e outros equipamentos em bom estado e limpos',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.5,
            opcoes: [],
          },
          {
            ordem: 19,
            secao: '4 - Equipamentos e Utensílios',
            pergunta: 'Utensílios íntegros, higienizados e de material adequado',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 20,
            secao: '4 - Equipamentos e Utensílios',
            pergunta: 'Presença de etiquetas de validade',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },

          // ── 5. Procedimentos Operacionais Padrão ──────────────────
          {
            ordem: 21,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'O princípio do PEPS (Primeiro que entra é o primeiro que sai) está sendo realizado?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 22,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'As prateleiras, janelas e demais instalações são higienizadas adequadamente?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 23,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'O local está limpo e organizado?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 24,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'Não existe mato ou entulho ao redor da cozinha?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: false,
            fotoObrigatoria: false,
            peso: 1.0,
            opcoes: [],
          },
          {
            ordem: 25,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'Não há materiais de limpeza próximo aos alimentos e/ou na área de manipulação?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 26,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'O descongelamento está sendo feito corretamente?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 27,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'A dedetização está sendo feita semestralmente (insetos e roedores)?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 2.0,
            opcoes: [],
          },
          {
            ordem: 28,
            secao: '5 - Procedimentos Operacionais Padrão',
            pergunta: 'Não há incidência de insetos e roedores no local?',
            tipoResposta: 'SIM_NAO',
            obrigatorio: true,
            isCritico: true,
            fotoObrigatoria: false,
            peso: 3.0,
            opcoes: [],
          },
        ],
      },
    },
  })

  console.log(`✅ Checklist SMEL criado! ID: ${checklist.id}`)
  console.log(`   28 itens em 5 seções`)
}

main()
  .catch((e) => { console.error('❌ Erro:', e); process.exit(1) })
  .finally(() => prisma.$disconnect())
